### ISSUE TITLE
[Feature Request] Add on screen buttons for actions

### ISSUE THREAD

**Issue by hXtreme** [pablolucianop/teach-dog-a-trick#4]
Using the website on a phone is very hard because you lack a keyboard to trigger tricks.

Having an on screen button/menu would make it a lot easier to use from a phone.

**Comment by pablolucianop** [comment]
Fixed the 'tap here to play dead' text button (in mobile version).
To play fetch, simply tap anywhere on the screen, using mobile, or clicking, in desktop.
If the dog learn more tricks, a menu will be useful. Thanks for the suggestion
